# Generated by Django 3.0.1 on 2020-01-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20191228_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Size'),
        ),
    ]
