# Generated by Django 3.0.1 on 2020-01-09 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200109_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Composition'),
        ),
    ]
