# Generated by Django 3.0.1 on 2020-01-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20200109_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer_name',
            field=models.CharField(default='Denis', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='denis.frunza@ix.co', max_length=254),
            preserve_default=False,
        ),
    ]
