# Generated by Django 3.0.1 on 2020-01-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20200112_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='product_id',
        ),
    ]
